
# Permessi
Permesso-Controllo: "ch.controllo"
Permesso-Set-Posizione: "ch.location"
Permesso-Reload: "ch.reload"

# Inserire tra le "" il comando che si vuole eseguire quando un utente ammetterà durante il controllo (cambia dal tipo di plugin es. LiteBans
# Ricorda di usare %player% per il nome dell'utente
# Ammissione
Comando-Console-Ban: "ban %player% 7d Ammissione Hack"

# Tempban Staff
Comando-Staff-Tempban: "tempban %player% 7d Ammissione Hack"

# Permaban Staff
Comando-Staff-Permaban: "ban %player% (Motivo)"



# Impostabile con il comando /setposizione direttamente dal gioco

Posizione-Controllo:
  world: "world"
  x: 0
  y: 0
  z: 0


